# Generated by Django 5.2.9 on 2026-01-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='popular',
            field=models.CharField(max_length=100),
        ),
    ]
