# Generated by Django 5.2.9 on 2026-01-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_bus_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='person',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
