# Generated by Django 5.2.9 on 2026-02-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_bus_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='popular',
            new_name='durations',
        ),
    ]
